version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_tracker
    ports:
      - "5432:5432"
