services:
  app:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/app/migrations
    entrypoint: >
      sh -c "flask db upgrade && python app.py"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0

  db:
    env_file:
      - .env
    image: postgres:15
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 5

