version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      SQLALCHEMY_DATABASE_URI: postgresql://user:password@db:5432/stock_tracker
      GOOGLE_CLIENT_ID: "your-client-id.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "your-client-secret"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_tracker
    ports:
      - "5432:5432"
