version: "3.9"
services:
  app:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
      
  db:
    env_file:
      - .env
    image: postgres:15
    ports:
      - "5432:5432"
